re-enable steps

diff --git a/.github/workflows/nightly-tests.yml b/.github/workflows/nightly-tests.yml
--- a/.github/workflows/nightly-tests.yml
+++ b/.github/workflows/nightly-tests.yml
@@ -14,114 +14,114 @@ env:
   POWDR_OPENVM_SEGMENT_DELTA: 10000
 
 jobs:
-  # check_if_needs_running:
-  #   runs-on: ubuntu-24.04
-  #   outputs:
-  #     status: ${{ steps.count.outputs.status }}
+  check_if_needs_running:
+    runs-on: ubuntu-24.04
+    outputs:
+      status: ${{ steps.count.outputs.status }}
 
-  #   steps:
-  #     - uses: actions/checkout@v4
-  #     - name: Count recent commits
-  #       id: count
-  #       run: echo "status=$(git log --oneline --since '24 hours ago' | wc -l)" >> $GITHUB_OUTPUT
+    steps:
+      - uses: actions/checkout@v4
+      - name: Count recent commits
+        id: count
+        run: echo "status=$(git log --oneline --since '24 hours ago' | wc -l)" >> $GITHUB_OUTPUT
 
-  # udeps:
-  #   runs-on: ubuntu-22.04
-  #   needs: check_if_needs_running
-  #   if: needs.check_if_needs_running.outputs.status > 0
+  udeps:
+    runs-on: ubuntu-22.04
+    needs: check_if_needs_running
+    if: needs.check_if_needs_running.outputs.status > 0
 
-  #   steps:
-  #     - name: Checkout repository
-  #       uses: actions/checkout@v4
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
 
-  #     - name: Install nightly toolchain
-  #       uses: actions-rs/toolchain@v1
-  #       with:
-  #         toolchain: nightly
-  #         override: true
+      - name: Install nightly toolchain
+        uses: actions-rs/toolchain@v1
+        with:
+          toolchain: nightly
+          override: true
 
-  #     - name: Run cargo-udeps
-  #       uses: aig787/cargo-udeps-action@v1
-  #       with:
-  #         version: "latest"
-  #         args: "--all-targets"
+      - name: Run cargo-udeps
+        uses: aig787/cargo-udeps-action@v1
+        with:
+          version: "latest"
+          args: "--all-targets"
 
-  # test_release:
-  #   runs-on: ubuntu-24.04
-  #   needs: check_if_needs_running
-  #   if: needs.check_if_needs_running.outputs.status > 0
+  test_release:
+    runs-on: ubuntu-24.04
+    needs: check_if_needs_running
+    if: needs.check_if_needs_running.outputs.status > 0
 
-  #   steps:
-  #     - uses: actions/checkout@v4
-  #       with:
-  #         submodules: recursive
-  #     - name: ⚡ Cache rust
-  #       uses: actions/cache@v4
-  #       with:
-  #         path: |
-  #           ~/.cargo/registry
-  #           ~/.cargo/git
-  #           target
-  #         key: ${{ runner.os }}-cargo-release-${{ hashFiles('**/Cargo.toml') }}
-  #     - name: Install Rust toolchain 1.85
-  #       run: rustup toolchain install 1.85
-  #     - name: Install nightly
-  #       run: rustup toolchain install nightly-2025-05-14 --component rust-src
-  #     - name: Install nightly
-  #       run: rustup toolchain install nightly-2025-02-14 --component rust-src
-  #     - name: Install riscv target
-  #       run: rustup target add riscv32imac-unknown-none-elf --toolchain nightly-2025-05-14
-  #     - name: Install test dependencies
-  #       run: sudo apt-get update && sudo apt-get install -y binutils-riscv64-unknown-elf lld
-  #     - name: Build
-  #       run: cargo build --all --release --all-features
-  #     - name: Run tests
-  #       run: cargo test --all --release --verbose --all-features --exclude powdr-openvm -- --include-ignored --nocapture --test-threads=2
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          submodules: recursive
+      - name: ⚡ Cache rust
+        uses: actions/cache@v4
+        with:
+          path: |
+            ~/.cargo/registry
+            ~/.cargo/git
+            target
+          key: ${{ runner.os }}-cargo-release-${{ hashFiles('**/Cargo.toml') }}
+      - name: Install Rust toolchain 1.85
+        run: rustup toolchain install 1.85
+      - name: Install nightly
+        run: rustup toolchain install nightly-2025-05-14 --component rust-src
+      - name: Install nightly
+        run: rustup toolchain install nightly-2025-02-14 --component rust-src
+      - name: Install riscv target
+        run: rustup target add riscv32imac-unknown-none-elf --toolchain nightly-2025-05-14
+      - name: Install test dependencies
+        run: sudo apt-get update && sudo apt-get install -y binutils-riscv64-unknown-elf lld
+      - name: Build
+        run: cargo build --all --release --all-features
+      - name: Run tests
+        run: cargo test --all --release --verbose --all-features --exclude powdr-openvm -- --include-ignored --nocapture --test-threads=2
 
-  # bench:
-  #   runs-on: warp-ubuntu-2404-x64-4x
-  #   permissions:
-  #     contents: write
-  #     deployments: write
-  #     pull-requests: write
+  bench:
+    runs-on: warp-ubuntu-2404-x64-4x
+    permissions:
+      contents: write
+      deployments: write
+      pull-requests: write
 
-  #   steps:
-  #     - uses: actions/checkout@v4
-  #       with:
-  #         submodules: recursive
-  #     - name: ⚡ Restore rust cache
-  #       id: cache
-  #       uses: WarpBuilds/cache/restore@v1
-  #       with:
-  #         path: |
-  #           ~/.cargo/registry/index/
-  #           ~/.cargo/registry/cache/
-  #           ~/.cargo/git/db/
-  #           target/
-  #           Cargo.lock
-  #         key: ${{ runner.os }}-cargo-pr-tests
-  #     - name: Install Rust toolchain nightly-2025-05-14 (with clippy and rustfmt)
-  #       run: rustup toolchain install nightly-2025-05-14 --component clippy,rustfmt,rust-src
-  #     - name: Install Rust toolchain 1.85
-  #       run: rustup toolchain install 1.85
-  #     - name: Install riscv target
-  #       run: rustup target add riscv32imac-unknown-none-elf --toolchain nightly-2025-05-14
-  #     - name: Install test dependencies
-  #       run: sudo apt-get update && sudo apt-get install -y binutils-riscv64-unknown-elf lld
-  #     - name: Run benchmarks
-  #       # we add `|| exit 1` to make sure the step fails if `cargo bench` fails
-  #       run: cargo bench --workspace --all-features -- --output-format bencher | tee output.txt || exit 1
-  #     - name: Store benchmark result
-  #       uses: benchmark-action/github-action-benchmark@v1
-  #       with:
-  #         name: Benchmarks
-  #         tool: "cargo"
-  #         output-file-path: output.txt
-  #         github-token: ${{ secrets.GITHUB_TOKEN }}
-  #         auto-push: true
-  #         alert-threshold: "120%"
-  #         comment-on-alert: true
-  #         summary-always: true
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          submodules: recursive
+      - name: ⚡ Restore rust cache
+        id: cache
+        uses: WarpBuilds/cache/restore@v1
+        with:
+          path: |
+            ~/.cargo/registry/index/
+            ~/.cargo/registry/cache/
+            ~/.cargo/git/db/
+            target/
+            Cargo.lock
+          key: ${{ runner.os }}-cargo-pr-tests
+      - name: Install Rust toolchain nightly-2025-05-14 (with clippy and rustfmt)
+        run: rustup toolchain install nightly-2025-05-14 --component clippy,rustfmt,rust-src
+      - name: Install Rust toolchain 1.85
+        run: rustup toolchain install 1.85
+      - name: Install riscv target
+        run: rustup target add riscv32imac-unknown-none-elf --toolchain nightly-2025-05-14
+      - name: Install test dependencies
+        run: sudo apt-get update && sudo apt-get install -y binutils-riscv64-unknown-elf lld
+      - name: Run benchmarks
+        # we add `|| exit 1` to make sure the step fails if `cargo bench` fails
+        run: cargo bench --workspace --all-features -- --output-format bencher | tee output.txt || exit 1
+      - name: Store benchmark result
+        uses: benchmark-action/github-action-benchmark@v1
+        with:
+          name: Benchmarks
+          tool: "cargo"
+          output-file-path: output.txt
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          auto-push: true
+          alert-threshold: "120%"
+          comment-on-alert: true
+          summary-always: true
 
   test_apc:
     runs-on: self-hosted
@@ -157,10 +157,10 @@ jobs:
           rm -rf results
           mkdir -p results
 
-      # - name: Run guest benchmarks
-      #   run: |
-      #     source .venv/bin/activate
-      #     bash ./openvm/scripts/run_guest_benches.sh
+      - name: Run guest benchmarks
+        run: |
+          source .venv/bin/activate
+          bash ./openvm/scripts/run_guest_benches.sh
 
       - name: Checkout openvm-reth-benchmark
         uses: actions/checkout@v4
@@ -169,35 +169,35 @@ jobs:
           ref: main
           path: openvm-reth-benchmark
 
-      # - name: Patch openvm-reth-benchmark to use local powdr
-      #   run: |
-      #     cd openvm-reth-benchmark
-      #     mkdir -p .cargo
-      #     echo '[patch."https://github.com/powdr-labs/powdr.git"]' > .cargo/config.toml
-      #     echo 'powdr-openvm = { path = "../openvm" }' >> .cargo/config.toml
-      #     echo 'powdr-riscv-elf = { path = "../riscv-elf" }' >> .cargo/config.toml
-      #     echo 'powdr-number = { path = "../number" }' >> .cargo/config.toml
-      #     echo 'powdr-autoprecompiles = { path = "../autoprecompiles" }' >> .cargo/config.toml
+      - name: Patch openvm-reth-benchmark to use local powdr
+        run: |
+          cd openvm-reth-benchmark
+          mkdir -p .cargo
+          echo '[patch."https://github.com/powdr-labs/powdr.git"]' > .cargo/config.toml
+          echo 'powdr-openvm = { path = "../openvm" }' >> .cargo/config.toml
+          echo 'powdr-riscv-elf = { path = "../riscv-elf" }' >> .cargo/config.toml
+          echo 'powdr-number = { path = "../number" }' >> .cargo/config.toml
+          echo 'powdr-autoprecompiles = { path = "../autoprecompiles" }' >> .cargo/config.toml
 
-      # - name: Run reth benchmark
-      #   run: |
-      #     source .venv/bin/activate
-      #     cd openvm-reth-benchmark
-      #     RES_DIR=reth
-      #     mkdir -p $RES_DIR
-      #     echo "export RPC_1=${{ secrets.RPC_1 }}" >> .env
+      - name: Run reth benchmark
+        run: |
+          source .venv/bin/activate
+          cd openvm-reth-benchmark
+          RES_DIR=reth
+          mkdir -p $RES_DIR
+          echo "export RPC_1=${{ secrets.RPC_1 }}" >> .env
 
-      #     # prove with no APCs
-      #     MODE="prove-stark" APC=0 ./run.sh
-      #     mv metrics.json $RES_DIR/noapc.json
-      #     # prove with 100 APCs, recording mem usage
-      #     MODE="prove-stark" APC=100 psrecord --include-children --interval 1 --log $RES_DIR/psrecord.csv --log-format csv --plot $RES_DIR/psrecord.png "./run.sh"
-      #     mv metrics.json $RES_DIR/100apc.json
+          # prove with no APCs
+          MODE="prove-stark" APC=0 ./run.sh
+          mv metrics.json $RES_DIR/noapc.json
+          # prove with 100 APCs, recording mem usage
+          MODE="prove-stark" APC=100 psrecord --include-children --interval 1 --log $RES_DIR/psrecord.csv --log-format csv --plot $RES_DIR/psrecord.png "./run.sh"
+          mv metrics.json $RES_DIR/100apc.json
 
-      #     python ../openvm/scripts/basic_metrics.py --csv $RES_DIR/noapc.json $RES_DIR/100apc.json > $RES_DIR/basic.csv
-      #     python ../openvm/scripts/plot_trace_cells.py -o $RES_DIR/trace_cells.png $RES_DIR/100apc.json > $RES_DIR/trace_cells.txt
+          python ../openvm/scripts/basic_metrics.py --csv $RES_DIR/noapc.json $RES_DIR/100apc.json > $RES_DIR/basic.csv
+          python ../openvm/scripts/plot_trace_cells.py -o $RES_DIR/trace_cells.png $RES_DIR/100apc.json > $RES_DIR/trace_cells.txt
 
-      #     mv $RES_DIR ../results/
+          mv $RES_DIR ../results/
 
       - name: Save revisions and run info
         run: |
