prevent silent failure, fix failure

diff --git a/.github/workflows/pr-tests.yml b/.github/workflows/pr-tests.yml
--- a/.github/workflows/pr-tests.yml
+++ b/.github/workflows/pr-tests.yml
@@ -276,7 +276,8 @@ jobs:
     - name: Install pilcom
       run: git clone https://github.com/0xPolygonHermez/pilcom.git  && cd pilcom && npm install
     - name: Run benchmarks
-      run: cargo bench --workspace --all-features -- --output-format bencher | tee output.txt
+      # we add `|| exit 1` to make sure the step fails if `cargo bench` fails
+      run: cargo bench --workspace --all-features -- --output-format bencher | tee output.txt || exit 1
     - name: Store benchmark result
       uses: benchmark-action/github-action-benchmark@v1
       with:
